package features

func freeGenesList() []string {
	return []string{"9N7polA",
		"K12polLF",
		"K12polLF (exo)",
		"ECOpolA",
		"KTHEAQpol",
		"KODpol",
		"Pwopol",
		"GBDpol (exo)",
		"GBDpol",
		"THEAQpolA",
		"Tlipol (exo)",
		"TthpolA",
		"Bstpol",
		"BstpolLF",
		"BsupolLF",
		"phi29pol",
		"9N7polA (CT)",
		"dbh",
		"T4gene43",
		"T7gene5",
		"T5gene122",
		"T4gene30",
		"ECOligA",
		"HSlig3",
		"HSlig4",
		"9N7lig",
		"Pfulig",
		"THEAQlig",
		"T4gene63",
		"ALPI",
		"RNAse A",
		"RNAse H",
		"EcoRIR",
		"EcoRIM",
		"PstIR",
		"PstIM",
		"MMLV_RT (mut H)",
		"MMLV_RT (lack H)",
		"TthRT",
		"T3RNAp",
		"T7RNAp",
		"SP6RNAp",
		"Eco31I",
		"Eco31IA",
		"Eco31IB",
		"SapIR",
		"SapIM1",
		"SapIM2",
		"XbaIR",
		"XbaIM",
		"NotIR (GC)",
		"NotIM",
		"SfiIR (cDNA)",
		"SfiIM",
		"EcoRV",
		"EcoRVM",
		"NcoIR",
		"NcoIM",
		"HindIIIR",
		"HindIIIM",
		"DpnIR",
		"Bst HF",
		"ETSSB",
		"T5gene12/13",
		"TthligK294R",
		"dromedNK",
		"TEV protease",
		"T4 PNK",
		"T4-BGT",
		"T7EI",
		"T4 PGD",
		"T4 g32",
		"P45",
		"BovDNTT",
		"DNA Topoisomerase 1B Vaccinia Virus",
		"lambda red operon",
		"UDG",
		"Fpg",
		"Endonuclease IV E. coli",
		"Endonuclease VIII E. coli",
		"Exonuclease III E. coli",
	}
}
